#!/usr/bin/env bash
set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "=== GureumPage 시크릿 셋업 ==="

# 1. Doppler CLI 설치 확인
if ! command -v doppler &> /dev/null; then
    echo "[1/5] Doppler CLI 설치 중..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install dopplerhq/cli/doppler
    else
        echo "Linux: https://docs.doppler.com/docs/install-cli 를 참고해 설치 후 재실행하세요."
        exit 1
    fi
else
    echo "[1/5] Doppler CLI: $(doppler --version)"
fi

# 2. 로그인 확인
echo "[2/5] Doppler 인증 확인..."
doppler me &> /dev/null || doppler login

# 3. 프로젝트 연결
echo "[3/5] 프로젝트 연결 (gureumpage / dev)..."
doppler setup --project gureumpage --config dev --no-prompt

# 4. local.properties 생성 (기존 sdk.dir 보존)
echo "[4/5] local.properties 생성..."
SDK_LINE=""
if [ -f "$PROJECT_ROOT/local.properties" ]; then
    SDK_LINE=$(grep "^sdk.dir=" "$PROJECT_ROOT/local.properties" || true)
fi

{
    echo "## Auto-generated by scripts/setup-secrets.sh — DO NOT EDIT MANUALLY"
    echo "## 갱신: bash scripts/setup-secrets.sh"
    if [ -n "$SDK_LINE" ]; then
        echo "$SDK_LINE"
    else
        echo "sdk.dir=${ANDROID_HOME:-$HOME/Library/Android/sdk}"
    fi
    doppler secrets download --no-file --format env --exclude GOOGLE_SERVICES_JSON \
        | grep -E "^(KAKAO_|NAVER_|ALADIN_|GOOGLE_WEB_CLIENT_ID)"
} > "$PROJECT_ROOT/local.properties"

# 5. google-services.json 복원
echo "[5/5] google-services.json 복원..."
doppler secrets get GOOGLE_SERVICES_JSON --plain \
    > "$PROJECT_ROOT/app/google-services.json"

echo ""
echo "완료! local.properties 및 app/google-services.json 생성됨."
echo "./gradlew assembleDebug 또는 Android Studio에서 Gradle sync를 실행하세요."
